// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/337587de8c13868283993bfacdcdd1a0f3291e7f/ejs-locals/index.d.ts
declare module 'ejs-locals' {
// Type definitions for ejs-locals
// Project: https://github.com/randometc/ejs-locals
// Definitions by: jt000 <https://github.com/jt000>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped



function ejsLocals(): Function;

export = ejsLocals;
}
